-- Annie's Log: notes, reminders, suggested reminders, chat state
-- Moxie (Annie's assistant) data layer

-- Notes: daily free-text notes
CREATE TABLE IF NOT EXISTS annie_log_notes (
  id          text PRIMARY KEY,
  content     text NOT NULL CHECK (char_length(content) <= 5000),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- Reminders: active and completed reminders
CREATE TABLE IF NOT EXISTS annie_log_reminders (
  id          text PRIMARY KEY,
  content     text NOT NULL CHECK (char_length(content) <= 500),
  due         text NOT NULL DEFAULT '' CHECK (char_length(due) <= 200),
  fingerprint text NOT NULL DEFAULT '',
  done        boolean NOT NULL DEFAULT false,
  done_at     timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- Suggested reminders: auto-extracted from notes, pending confirmation
CREATE TABLE IF NOT EXISTS annie_log_suggested_reminders (
  id          text PRIMARY KEY,
  content     text NOT NULL CHECK (char_length(content) <= 500),
  due         text NOT NULL DEFAULT '' CHECK (char_length(due) <= 200),
  fingerprint text NOT NULL DEFAULT '',
  status      text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'dismissed')),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- Contacts: Annie's contact book
CREATE TABLE IF NOT EXISTS annie_contacts (
  id          text PRIMARY KEY,
  name        text NOT NULL DEFAULT '',
  phone       text NOT NULL DEFAULT '',
  email       text NOT NULL DEFAULT '',
  notes       text NOT NULL DEFAULT '',
  source      text NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'suggested', 'import')),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- Suggested contacts: auto-extracted, pending confirmation
CREATE TABLE IF NOT EXISTS annie_suggested_contacts (
  id          text PRIMARY KEY,
  name        text NOT NULL DEFAULT '',
  phone       text NOT NULL DEFAULT '',
  email       text NOT NULL DEFAULT '',
  notes       text NOT NULL DEFAULT '',
  status      text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'dismissed')),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- Chat state: saved chats and current history for Moxie web UI
CREATE TABLE IF NOT EXISTS annie_chat_state (
  id          text PRIMARY KEY DEFAULT 'default',
  history     jsonb NOT NULL DEFAULT '[]'::jsonb,
  saved_chats jsonb NOT NULL DEFAULT '[]'::jsonb,
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- Deliverables: files generated by Moxie
CREATE TABLE IF NOT EXISTS annie_deliverables (
  id          text PRIMARY KEY,
  filename    text NOT NULL CHECK (char_length(filename) <= 160),
  content     bytea,
  mime_type   text NOT NULL DEFAULT 'application/octet-stream',
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_annie_log_notes_created_at ON annie_log_notes (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_annie_log_reminders_done ON annie_log_reminders (done, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_annie_log_reminders_fingerprint ON annie_log_reminders (fingerprint);
CREATE INDEX IF NOT EXISTS idx_annie_log_suggested_status ON annie_log_suggested_reminders (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_annie_contacts_name ON annie_contacts (name);
CREATE INDEX IF NOT EXISTS idx_annie_suggested_contacts_status ON annie_suggested_contacts (status, created_at DESC);

-- Enable RLS
ALTER TABLE annie_log_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE annie_log_reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE annie_log_suggested_reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE annie_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE annie_suggested_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE annie_chat_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE annie_deliverables ENABLE ROW LEVEL SECURITY;

-- RLS policies: service role bypasses RLS, so these are for future anon/key use
-- For now, all access goes through the service role in the Express app
CREATE POLICY "service_role_all_annie_log_notes ON annie_log_notes FOR ALL USING (true);
CREATE POLICY "service_role_all_annie_log_reminders ON annie_log_reminders FOR ALL USING (true);
CREATE POLICY "service_role_all_annie_log_suggested ON annie_log_suggested_reminders FOR ALL USING (true);
CREATE POLICY "service_role_all_annie_contacts ON annie_contacts FOR ALL USING (true);
CREATE POLICY "service_role_all_annie_suggested_contacts ON annie_suggested_contacts FOR ALL USING (true);
CREATE POLICY "service_role_all_annie_chat_state ON annie_chat_state FOR ALL USING (true);
CREATE POLICY "service_role_all_annie_deliverables ON annie_deliverables FOR ALL USING (true);
